# Generated by Django 6.0.4 on 2026-05-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'Enrollment Request'), ('enrollment_invite', 'Enrollment Invite'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('course_admin_assigned', 'Course Admin Assigned')], max_length=30),
        ),
    ]
