# Generated by Django 6.0.4 on 2026-05-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('enrollment_request', 'Enrollment Request'), ('enrollment_invite', 'Enrollment Invite'), ('enrollment_approved', 'Enrollment Approved'), ('enrollment_rejected', 'Enrollment Rejected'), ('course_admin_assigned', 'Course Admin Assigned'), ('course_admin_invite', 'Course Admin Invite')], max_length=30),
        ),
    ]
