# Generated by Django 6.0.4 on 2026-05-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_studentperiodsummary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='grade',
            name='title',
            field=models.CharField(default='Grade', max_length=200),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='assignment',
        ),
    ]
