# Generated by Django 6.0.4 on 2026-05-04 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_dailyscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('bonus_score', models.PositiveIntegerField(default=0)),
                ('exam_score', models.PositiveIntegerField(default=0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_summaries', to='crm.courseperiod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'period', 'week_number')},
            },
        ),
    ]
